services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - webnet
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend
    volumes:
      - ./app/dist:/app
    depends_on:
      - backend
    networks:
      - webnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
